In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [128]:
from sklearn.linear_model import LogisticRegression, LogisticRegressionCV

In [9]:
from sklearn.metrics import confusion_matrix, classification_report

In [11]:
df_train = pd.read_csv('C:/Users/Administrator/Desktop/PM/ChurnData.csv')

In [13]:
df_train.head(5)

Unnamed: 0 state  account_length      area_code international_plan  \
0           1    KS             128  area_code_415                 no   
1           2    OH             107  area_code_415                 no   
2           3    NJ             137  area_code_415                 no   
3           4    OH              84  area_code_408                yes   
4           5    OK              75  area_code_415                yes   

  voice_mail_plan  number_vmail_messages  total_day_minutes  total_day_calls  \
0             yes                     25              265.1              110   
1             yes                     26              161.6              123   
2              no                      0              243.4              114   
3              no                      0              299.4               71   
4              no                      0              166.7              113   

   total_day_charge  ...    total_eve_calls  total_eve_charge  \
0             45.07  ...                 99             16.78   
1             27.47  ...                103             16.62   
2             41.38  ...                110             10.30   
3             50.90  ...                 88              5.26   
4             28.34  ...                122             12.61   

   total_night_minutes  total_night_calls  total_night_charge  \
0                244.7                 91               11.01   
1                254.4                103               11.45   
2                162.6                104                7.32   
3                196.9                 89                8.86   
4                186.9                121                8.41   

   total_intl_minutes  total_intl_calls  total_intl_charge  \
0                10.0                 3               2.70   
1                13.7                 3               3.70   
2                12.2                 5               3.29   
3                 6.6                 7               1.78   
4                10.1                 3               2.73   

   number_customer_service_calls  churn  
0                              1     no  
1                              1     no  
2                              0     no  
3                              2     no  
4                              3     no  

[5 rows x 21 columns]

In [14]:
del df_train['Unnamed: 0']

In [15]:
df_train.head()

state  account_length      area_code international_plan voice_mail_plan  \
0    KS             128  area_code_415                 no             yes   
1    OH             107  area_code_415                 no             yes   
2    NJ             137  area_code_415                 no              no   
3    OH              84  area_code_408                yes              no   
4    OK              75  area_code_415                yes              no   

   number_vmail_messages  total_day_minutes  total_day_calls  \
0                     25              265.1              110   
1                     26              161.6              123   
2                      0              243.4              114   
3                      0              299.4               71   
4                      0              166.7              113   

   total_day_charge  total_eve_minutes  total_eve_calls  total_eve_charge  \
0             45.07              197.4               99             16.78   
1             27.47              195.5              103             16.62   
2             41.38              121.2              110             10.30   
3             50.90               61.9               88              5.26   
4             28.34              148.3              122             12.61   

   total_night_minutes  total_night_calls  total_night_charge  \
0                244.7                 91               11.01   
1                254.4                103               11.45   
2                162.6                104                7.32   
3                196.9                 89                8.86   
4                186.9                121                8.41   

   total_intl_minutes  total_intl_calls  total_intl_charge  \
0                10.0                 3               2.70   
1                13.7                 3               3.70   
2                12.2                 5               3.29   
3                 6.6                 7               1.78   
4                10.1                 3               2.73   

   number_customer_service_calls churn  
0                              1    no  
1                              1    no  
2                              0    no  
3                              2    no  
4                              3    no

In [16]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3333 entries, 0 to 3332
Data columns (total 20 columns):
state                            3333 non-null object
account_length                   3333 non-null int64
area_code                        3333 non-null object
international_plan               3333 non-null object
voice_mail_plan                  3333 non-null object
number_vmail_messages            3333 non-null int64
total_day_minutes                3333 non-null float64
total_day_calls                  3333 non-null int64
total_day_charge                 3333 non-null float64
total_eve_minutes                3333 non-null float64
total_eve_calls                  3333 non-null int64
total_eve_charge                 3333 non-null float64
total_night_minutes              3333 non-null float64
total_night_calls                3333 non-null int64
total_night_charge               3333 non-null float64
total_intl_minutes               3333 non-null float64
total_intl_calls           

In [17]:
df_train.columns

Index(['state', 'account_length', 'area_code', 'international_plan',
       'voice_mail_plan', 'number_vmail_messages', 'total_day_minutes',
       'total_day_calls', 'total_day_charge', 'total_eve_minutes',
       'total_eve_calls', 'total_eve_charge', 'total_night_minutes',
       'total_night_calls', 'total_night_charge', 'total_intl_minutes',
       'total_intl_calls', 'total_intl_charge',
       'number_customer_service_calls', 'churn'],
      dtype='object')

In [18]:
x = np.array(df_train[['state', 'account_length', 'area_code', 'international_plan',
       'voice_mail_plan', 'number_vmail_messages', 'total_day_minutes',
       'total_day_calls', 'total_day_charge', 'total_eve_minutes',
       'total_eve_calls', 'total_eve_charge', 'total_night_minutes',
       'total_night_calls', 'total_night_charge', 'total_intl_minutes',
       'total_intl_calls', 'total_intl_charge',
       'number_customer_service_calls']])

In [20]:
y = np.array(df_train['churn'])

In [21]:
model = LogisticRegression()

In [23]:
from sklearn.preprocessing import LabelEncoder

In [34]:
tras = LabelEncoder()

In [43]:
df_train['area_code_tr'] = tras.fit_transform(df_train['area_code'])

In [46]:
df_train.columns

Index(['state', 'account_length', 'area_code', 'international_plan',
       'voice_mail_plan', 'number_vmail_messages', 'total_day_minutes',
       'total_day_calls', 'total_day_charge', 'total_eve_minutes',
       'total_eve_calls', 'total_eve_charge', 'total_night_minutes',
       'total_night_calls', 'total_night_charge', 'total_intl_minutes',
       'total_intl_calls', 'total_intl_charge',
       'number_customer_service_calls', 'churn', 'state_tr', 'area_code_tr'],
      dtype='object')

In [49]:
del df_train['area_code']

In [50]:
df_train.columns

Index(['account_length', 'international_plan', 'voice_mail_plan',
       'number_vmail_messages', 'total_day_minutes', 'total_day_calls',
       'total_day_charge', 'total_eve_minutes', 'total_eve_calls',
       'total_eve_charge', 'total_night_minutes', 'total_night_calls',
       'total_night_charge', 'total_intl_minutes', 'total_intl_calls',
       'total_intl_charge', 'number_customer_service_calls', 'churn',
       'state_tr', 'area_code_tr'],
      dtype='object')

In [101]:
#df_dummies = pd.get_dummies(df_train,prefix=True,drop_first=True)

In [64]:
df_train['target_churn_dum'] = pd.get_dummies(df_train.churn,prefix='churn',drop_first=True)

In [65]:
df_train.columns

Index(['account_length', 'international_plan', 'voice_mail_plan',
       'number_vmail_messages', 'total_day_minutes', 'total_day_calls',
       'total_day_charge', 'total_eve_minutes', 'total_eve_calls',
       'total_eve_charge', 'total_night_minutes', 'total_night_calls',
       'total_night_charge', 'total_intl_minutes', 'total_intl_calls',
       'total_intl_charge', 'number_customer_service_calls', 'churn',
       'state_tr', 'area_code_tr', 'int_plan_dum', 'voic_mail_dum',
       'target_churn_dum'],
      dtype='object')

In [66]:
del df_train['international_plan']

In [67]:
del df_train['voice_mail_plan']

In [68]:
del df_train['churn']

In [69]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3333 entries, 0 to 3332
Data columns (total 20 columns):
account_length                   3333 non-null int64
number_vmail_messages            3333 non-null int64
total_day_minutes                3333 non-null float64
total_day_calls                  3333 non-null int64
total_day_charge                 3333 non-null float64
total_eve_minutes                3333 non-null float64
total_eve_calls                  3333 non-null int64
total_eve_charge                 3333 non-null float64
total_night_minutes              3333 non-null float64
total_night_calls                3333 non-null int64
total_night_charge               3333 non-null float64
total_intl_minutes               3333 non-null float64
total_intl_calls                 3333 non-null int64
total_intl_charge                3333 non-null float64
number_customer_service_calls    3333 non-null int64
state_tr                         3333 non-null int64
area_code_tr                 

In [70]:
from sklearn.model_selection import train_test_split

In [71]:
df_train.columns

Index(['account_length', 'number_vmail_messages', 'total_day_minutes',
       'total_day_calls', 'total_day_charge', 'total_eve_minutes',
       'total_eve_calls', 'total_eve_charge', 'total_night_minutes',
       'total_night_calls', 'total_night_charge', 'total_intl_minutes',
       'total_intl_calls', 'total_intl_charge',
       'number_customer_service_calls', 'state_tr', 'area_code_tr',
       'int_plan_dum', 'voic_mail_dum', 'target_churn_dum'],
      dtype='object')

In [74]:
X = df_train[['account_length', 'number_vmail_messages', 'total_day_minutes',
       'total_day_calls', 'total_day_charge', 'total_eve_minutes',
       'total_eve_calls', 'total_eve_charge', 'total_night_minutes',
       'total_night_calls', 'total_night_charge', 'total_intl_minutes',
       'total_intl_calls', 'total_intl_charge',
       'number_customer_service_calls', 'state_tr', 'area_code_tr',
       'int_plan_dum', 'voic_mail_dum']]
Y = df_train['target_churn_dum']

In [76]:
xtrain,xtest,ytrain,ytest=train_test_split(X,Y,test_size=0.20)

In [77]:
xtrain.shape,xtest.shape,ytrain.shape,ytest.shape

((2666, 19), (667, 19), (2666,), (667,))

In [78]:
model = LogisticRegression()

In [82]:
model.fit(xtrain,ytrain)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [83]:
model.score(xtrain,ytrain) #training accuracy

0.8555888972243061

In [85]:
model.score(xtest,ytest) # test accuracy

0.8770614692653673

In [93]:
temp = model.predict_proba(xtest)

In [103]:
# predicted value 0 means 'no churn'
# predicted value 1 means 'churn'

In [114]:
diff = temp[:,-2] - temp[:,-1]
diff

array([ 0.74945678,  0.95822995,  0.45905366,  0.45117729,  0.93219456,
        0.93187313,  0.7857715 ,  0.91162705,  0.75456912,  0.96040668,
        0.85973109,  0.82247041,  0.74339232,  0.9224642 ,  0.89366118,
        0.93572488,  0.8929282 ,  0.79537227,  0.83918137,  0.62532582,
        0.72073179,  0.07597114,  0.61728521,  0.59189076,  0.92613616,
        0.88267905,  0.59965675,  0.03852792,  0.90966833, -0.3156803 ,
        0.91255483,  0.75031193,  0.98119328, -0.06826902, -0.70722719,
        0.80836128,  0.58475429,  0.74865779,  0.85508482,  0.87071358,
        0.85401398,  0.74466586,  0.93947039,  0.79535922,  0.88893061,
        0.70052142,  0.85822166,  0.78234956,  0.89630117,  0.53761303,
        0.888282  ,  0.87136653,  0.27428995,  0.9200331 , -0.82832016,
        0.57712664,  0.09100522,  0.92278649,  0.73229187,  0.35437951,
        0.86649033,  0.91119237,  0.68835938,  0.57177629,  0.96537365,
        0.97179054,  0.76975238,  0.43527139,  0.93643564, -0.38

In [117]:
pd.Series(np.where(diff < 0.10,'bad','good')).value_counts()

good    613
bad      54
dtype: int64

In [127]:
54/667

0.08095952023988005

In [98]:
temp
# if the probability of no churn > 0.5, no churn, churn

array([[0.87472839, 0.12527161],
       [0.97911498, 0.02088502],
       [0.72952683, 0.27047317],
       ...,
       [0.92563359, 0.07436641],
       [0.91594468, 0.08405532],
       [0.98181232, 0.01818768]])

In [120]:
pred_y_60 = np.where(temp[:,-2] > 0.6, 0,1)

In [121]:
confusion_matrix(ytest,pred_y_60)

array([[547,  36],
       [ 49,  35]], dtype=int64)

In [122]:
print(classification_report(ytest,pred_y_60))

             precision    recall  f1-score   support

          0       0.92      0.94      0.93       583
          1       0.49      0.42      0.45        84

avg / total       0.86      0.87      0.87       667



In [125]:
# since this is reducing the overall accuracy and without improving the class 1 (churn) accuracy,
# fallback, this step should not be pursued
pred_y_70 = np.where(temp[:,-2] > 0.7, 0,1)
confusion_matrix(ytest,pred_y_70)

array([[524,  59],
       [ 42,  42]], dtype=int64)

In [126]:
print(classification_report(ytest,pred_y_70))

             precision    recall  f1-score   support

          0       0.93      0.90      0.91       583
          1       0.42      0.50      0.45        84

avg / total       0.86      0.85      0.85       667



In [106]:
pred_y = model.predict(xtest)

In [107]:
confusion_matrix(ytest,pred_y)

array([[565,  18],
       [ 64,  20]], dtype=int64)

In [112]:
print(classification_report(ytest,pred_y))

             precision    recall  f1-score   support

          0       0.90      0.97      0.93       583
          1       0.53      0.24      0.33        84

avg / total       0.85      0.88      0.86       667



In [102]:
df_train.head()

account_length  number_vmail_messages  total_day_minutes  total_day_calls  \
0             128                     25              265.1              110   
1             107                     26              161.6              123   
2             137                      0              243.4              114   
3              84                      0              299.4               71   
4              75                      0              166.7              113   

   total_day_charge  total_eve_minutes  total_eve_calls  total_eve_charge  \
0             45.07              197.4               99             16.78   
1             27.47              195.5              103             16.62   
2             41.38              121.2              110             10.30   
3             50.90               61.9               88              5.26   
4             28.34              148.3              122             12.61   

   total_night_minutes  total_night_calls  total_night_charge  \
0                244.7                 91               11.01   
1                254.4                103               11.45   
2                162.6                104                7.32   
3                196.9                 89                8.86   
4                186.9                121                8.41   

   total_intl_minutes  total_intl_calls  total_intl_charge  \
0                10.0                 3               2.70   
1                13.7                 3               3.70   
2                12.2                 5               3.29   
3                 6.6                 7               1.78   
4                10.1                 3               2.73   

   number_customer_service_calls  state_tr  area_code_tr  int_plan_dum  \
0                              1        16             1             0   
1                              1        35             1             0   
2                              0        31             1             0   
3                              2        35             0             1   
4                              3        36             1             1   

   voic_mail_dum  target_churn_dum  
0              1                 0  
1              1                 0  
2              0                 0  
3              0                 0  
4              0                 0

In [88]:
np.round(model.coef_,2)

array([[-0.  ,  0.02,  0.01, -0.  ,  0.01,  0.01, -0.01, -0.01,  0.  ,
        -0.  , -0.  ,  0.04, -0.12,  0.03,  0.47,  0.  , -0.07,  2.02,
        -1.53]])